site_name: SoftDes Desafio Docs

nav:
    - Home: index.md
    - API: api.md
    - Aluno: aluno.md
    - Professor: professor.md
    - Guia de Desenvolvimento: guia_des.md

theme: material

plugins:
  - search
  - mkdocstrings:
      watch:
        - src