site_name: SoftDes Desafio Docs
site_url: https://brunakimura.github.io/softdes-desafios/
repo_url: https://github.com/BrunaKimura/softdes-desafios
repo_name: BrunaKimura/softdes-desafios

nav:
    - Home: index.md
    - API: api.md
    - Aluno: aluno.md
    - Professor: professor.md
    - Guia de Desenvolvimento: guia_des.md

theme: material

plugins:
  - search
  - mkdocstrings:
      watch:
        - src